### ISSUE TITLE
CoaL on KVM can't mount usbkey

### ISSUE THREAD

**Issue by gochist** [joyent/triton#219]
Current CoaL on KVM can't mount usbkey as below.

```
[root@headnode (june-hp650-2) ~]# diskinfo -Hp
-       c1t0d0  Virtio  Block Device    64424509440     no      no
```
```
./sdc-usbkey -v mount 
[ 66] ensuring usb key is mounted... 
[ 108] configured usbkey mountpoint: "/mnt/usbkey" 
sdc-usbkey: error: VError: no pcfs devices found 
  at missing (/opt/smartdc/lib/usbkey.js:529:18) 
  at /opt/smartdc/lib/usbkey.js:710:21 
  at /opt/smartdc/lib/usbkey.js:266:13 
  at /opt/smartdc/node_modules/vasync/lib/vasync.js:96:5 
  at /opt/smartdc/lib/usbkey.js:257:21 
  at /opt/smartdc/lib/oscmds.js:246:17 
  at ChildProcess.exithandler (child_process.js:641:7) 
  at ChildProcess.EventEmitter.emit (events.js:98:17) 
  at maybeClose (child_process.js:743:16) 
  at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

As @jclulow mentioned in https://github.com/joyent/sdcadm/issues/25#issuecomment-245766420, changing disk driver/model from "virtio" to "ide" works for me.

```
[root@headnode (june-hp650-2) ~]# diskinfo -Hp
ATA     c0d0                    -        -                   4000260096   no  no 
-       c1t0d0                  Virtio   Block Device       64424509440   no  no 
```

```
[root@headnode (june-hp650-2) ~]# sdc-usbkey -v mount
[    42] ensuring usb key is mounted...
[    62] configured usbkey mountpoint: "/mnt/usbkey"
[   220] candidate devices: /dev/dsk/c0d0p1
[   221] fetching mount status for "/mnt/usbkey"
[   221] fetching mount information for "/mnt/usbkey"
[   227] "/mnt/usbkey" is not mounted.
[   227] mounting "/dev/dsk/c0d0p1" @ "/mnt/usbkey".
[   228] mount args: -F pcfs -o foldcase,noatime,hidden,clamptime,rw /dev/dsk/c0d0p1 /mnt/usbkey
[  6421] fetching mount status for "/mnt/usbkey"
[  6421] fetching mount information for "/mnt/usbkey"
[  6433] checking marker file...
[  6435] filesystem is mounted at "/mnt/usbkey"
/mnt/usbkey
```

**Comment by gochist** [comment]
I've made a review request at https://cr.joyent.us/#/c/863/
